[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "4hFWErito2uEohRQ2eoSv39xyKjLrcuPARCks8iDjX62"

[programs.devnet]
solana_twitter = "4hFWErito2uEohRQ2eoSv39xyKjLrcuPARCks8iDjX62"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
types = "app/idl/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
