[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "2eyJNpUiqaLghKUctM91UQET66Yx8BVbds2LvVvjd1Cg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/batman/.config/solana/solana-twitter-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
